"""Add content, person, and related models

Revision ID: 32d54dd444e9
Revises: f313eabe0cd1
Create Date: 2025-11-08 16:04:38.147079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32d54dd444e9'
down_revision: Union[str, None] = 'f313eabe0cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tvdb_alias_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.Enum('content', 'person', name='alias_entity_type_enum'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alias_entity', 'alias', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_alias_name_search', 'alias', ['name'], unique=False)
    op.create_index(op.f('ix_alias_entity_id'), 'alias', ['entity_id'], unique=False)
    op.create_index(op.f('ix_alias_entity_type'), 'alias', ['entity_type'], unique=False)
    op.create_index(op.f('ix_alias_id'), 'alias', ['id'], unique=False)
    op.create_index(op.f('ix_alias_tvdb_alias_id'), 'alias', ['tvdb_alias_id'], unique=False)
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tvdb_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('series', 'movie', name='content_type_enum'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('backdrop_url', sa.String(length=500), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('original_country', sa.String(length=10), nullable=True),
    sa.Column('popularity_score', sa.Float(), nullable=False),
    sa.Column('tvdb_last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_content_name_search', 'content', ['name'], unique=False)
    op.create_index('idx_content_popularity', 'content', ['popularity_score'], unique=False)
    op.create_index(op.f('ix_content_content_type'), 'content', ['content_type'], unique=False)
    op.create_index(op.f('ix_content_id'), 'content', ['id'], unique=False)
    op.create_index(op.f('ix_content_last_synced_at'), 'content', ['last_synced_at'], unique=False)
    op.create_index(op.f('ix_content_name'), 'content', ['name'], unique=False)
    op.create_index(op.f('ix_content_slug'), 'content', ['slug'], unique=True)
    op.create_index(op.f('ix_content_tvdb_id'), 'content', ['tvdb_id'], unique=True)
    op.create_index(op.f('ix_content_year'), 'content', ['year'], unique=False)
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tvdb_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_genre_id'), 'genre', ['id'], unique=False)
    op.create_index(op.f('ix_genre_slug'), 'genre', ['slug'], unique=True)
    op.create_index(op.f('ix_genre_tvdb_id'), 'genre', ['tvdb_id'], unique=True)
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tvdb_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_place', sa.String(length=255), nullable=True),
    sa.Column('popularity_score', sa.Float(), nullable=False),
    sa.Column('tvdb_last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_person_full_name_search', 'person', ['full_name'], unique=False)
    op.create_index('idx_person_popularity', 'person', ['popularity_score'], unique=False)
    op.create_index(op.f('ix_person_full_name'), 'person', ['full_name'], unique=False)
    op.create_index(op.f('ix_person_id'), 'person', ['id'], unique=False)
    op.create_index(op.f('ix_person_last_name'), 'person', ['last_name'], unique=False)
    op.create_index(op.f('ix_person_last_synced_at'), 'person', ['last_synced_at'], unique=False)
    op.create_index(op.f('ix_person_slug'), 'person', ['slug'], unique=True)
    op.create_index(op.f('ix_person_tvdb_id'), 'person', ['tvdb_id'], unique=True)
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('content', 'person', name='sync_entity_type_enum'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('tvdb_id', sa.Integer(), nullable=True),
    sa.Column('sync_status', sa.Enum('success', 'failed', 'partial', name='sync_status_enum'), nullable=False),
    sa.Column('sync_type', sa.Enum('full', 'incremental', 'metadata_only', name='sync_type_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_log_entity', 'sync_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_sync_log_status_time', 'sync_log', ['sync_status', 'synced_at'], unique=False)
    op.create_index(op.f('ix_sync_log_entity_id'), 'sync_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_sync_log_entity_type'), 'sync_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_sync_log_id'), 'sync_log', ['id'], unique=False)
    op.create_index(op.f('ix_sync_log_sync_status'), 'sync_log', ['sync_status'], unique=False)
    op.create_index(op.f('ix_sync_log_synced_at'), 'sync_log', ['synced_at'], unique=False)
    op.create_index(op.f('ix_sync_log_tvdb_id'), 'sync_log', ['tvdb_id'], unique=False)
    op.create_table('content_genre',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'genre_id')
    )
    op.create_table('credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tvdb_credit_id', sa.Integer(), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role_type', sa.Enum('actor', 'director', 'writer', 'producer', 'executive_producer', 'cinematographer', 'composer', 'editor', 'crew', name='role_type_enum'), nullable=False),
    sa.Column('character_name', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'person_id', 'role_type', 'character_name', name='uq_content_person_role_character')
    )
    op.create_index('idx_credit_content_sort', 'credit', ['content_id', 'sort_order'], unique=False)
    op.create_index('idx_credit_person_content', 'credit', ['person_id', 'content_id'], unique=False)
    op.create_index(op.f('ix_credit_content_id'), 'credit', ['content_id'], unique=False)
    op.create_index(op.f('ix_credit_id'), 'credit', ['id'], unique=False)
    op.create_index(op.f('ix_credit_person_id'), 'credit', ['person_id'], unique=False)
    op.create_index(op.f('ix_credit_role_type'), 'credit', ['role_type'], unique=False)
    op.create_index(op.f('ix_credit_tvdb_credit_id'), 'credit', ['tvdb_credit_id'], unique=False)
    op.create_table('movie_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('budget', sa.BigInteger(), nullable=True),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('production_company', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_detail_content_id'), 'movie_detail', ['content_id'], unique=True)
    op.create_index(op.f('ix_movie_detail_id'), 'movie_detail', ['id'], unique=False)
    op.create_table('series_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('number_of_seasons', sa.Integer(), nullable=True),
    sa.Column('number_of_episodes', sa.Integer(), nullable=True),
    sa.Column('average_runtime', sa.Integer(), nullable=True),
    sa.Column('first_air_date', sa.Date(), nullable=True),
    sa.Column('last_air_date', sa.Date(), nullable=True),
    sa.Column('network', sa.String(length=100), nullable=True),
    sa.Column('production_company', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_detail_content_id'), 'series_detail', ['content_id'], unique=True)
    op.create_index(op.f('ix_series_detail_id'), 'series_detail', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_series_detail_id'), table_name='series_detail')
    op.drop_index(op.f('ix_series_detail_content_id'), table_name='series_detail')
    op.drop_table('series_detail')
    op.drop_index(op.f('ix_movie_detail_id'), table_name='movie_detail')
    op.drop_index(op.f('ix_movie_detail_content_id'), table_name='movie_detail')
    op.drop_table('movie_detail')
    op.drop_index(op.f('ix_credit_tvdb_credit_id'), table_name='credit')
    op.drop_index(op.f('ix_credit_role_type'), table_name='credit')
    op.drop_index(op.f('ix_credit_person_id'), table_name='credit')
    op.drop_index(op.f('ix_credit_id'), table_name='credit')
    op.drop_index(op.f('ix_credit_content_id'), table_name='credit')
    op.drop_index('idx_credit_person_content', table_name='credit')
    op.drop_index('idx_credit_content_sort', table_name='credit')
    op.drop_table('credit')
    op.drop_table('content_genre')
    op.drop_index(op.f('ix_sync_log_tvdb_id'), table_name='sync_log')
    op.drop_index(op.f('ix_sync_log_synced_at'), table_name='sync_log')
    op.drop_index(op.f('ix_sync_log_sync_status'), table_name='sync_log')
    op.drop_index(op.f('ix_sync_log_id'), table_name='sync_log')
    op.drop_index(op.f('ix_sync_log_entity_type'), table_name='sync_log')
    op.drop_index(op.f('ix_sync_log_entity_id'), table_name='sync_log')
    op.drop_index('idx_sync_log_status_time', table_name='sync_log')
    op.drop_index('idx_sync_log_entity', table_name='sync_log')
    op.drop_table('sync_log')
    op.drop_index(op.f('ix_person_tvdb_id'), table_name='person')
    op.drop_index(op.f('ix_person_slug'), table_name='person')
    op.drop_index(op.f('ix_person_last_synced_at'), table_name='person')
    op.drop_index(op.f('ix_person_last_name'), table_name='person')
    op.drop_index(op.f('ix_person_id'), table_name='person')
    op.drop_index(op.f('ix_person_full_name'), table_name='person')
    op.drop_index('idx_person_popularity', table_name='person')
    op.drop_index('idx_person_full_name_search', table_name='person')
    op.drop_table('person')
    op.drop_index(op.f('ix_genre_tvdb_id'), table_name='genre')
    op.drop_index(op.f('ix_genre_slug'), table_name='genre')
    op.drop_index(op.f('ix_genre_id'), table_name='genre')
    op.drop_table('genre')
    op.drop_index(op.f('ix_content_year'), table_name='content')
    op.drop_index(op.f('ix_content_tvdb_id'), table_name='content')
    op.drop_index(op.f('ix_content_slug'), table_name='content')
    op.drop_index(op.f('ix_content_name'), table_name='content')
    op.drop_index(op.f('ix_content_last_synced_at'), table_name='content')
    op.drop_index(op.f('ix_content_id'), table_name='content')
    op.drop_index(op.f('ix_content_content_type'), table_name='content')
    op.drop_index('idx_content_popularity', table_name='content')
    op.drop_index('idx_content_name_search', table_name='content')
    op.drop_table('content')
    op.drop_index(op.f('ix_alias_tvdb_alias_id'), table_name='alias')
    op.drop_index(op.f('ix_alias_id'), table_name='alias')
    op.drop_index(op.f('ix_alias_entity_type'), table_name='alias')
    op.drop_index(op.f('ix_alias_entity_id'), table_name='alias')
    op.drop_index('idx_alias_name_search', table_name='alias')
    op.drop_index('idx_alias_entity', table_name='alias')
    op.drop_table('alias')
    # ### end Alembic commands ###
