"""add_season_and_episode_tables

Revision ID: c53a0797d682
Revises: 32d54dd444e9
Create Date: 2025-11-09 23:57:34.887518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c53a0797d682'
down_revision: Union[str, None] = '32d54dd444e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tvdb_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('season_type', sa.String(length=100), nullable=True),
    sa.Column('season_type_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_season_content', 'season', ['content_id'], unique=False)
    op.create_index('idx_season_number', 'season', ['content_id', 'season_number'], unique=False)
    op.create_index('idx_season_tvdb', 'season', ['tvdb_id'], unique=False)
    op.create_index(op.f('ix_season_id'), 'season', ['id'], unique=False)
    op.create_index(op.f('ix_season_season_number'), 'season', ['season_number'], unique=False)
    op.create_index(op.f('ix_season_tvdb_id'), 'season', ['tvdb_id'], unique=True)
    op.create_table('episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tvdb_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('absolute_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('aired', sa.Date(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('is_movie', sa.Integer(), nullable=True),
    sa.Column('finale_type', sa.String(length=50), nullable=True),
    sa.Column('airs_before_season', sa.Integer(), nullable=True),
    sa.Column('airs_before_episode', sa.Integer(), nullable=True),
    sa.Column('airs_after_season', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_episode_aired', 'episode', ['aired'], unique=False)
    op.create_index('idx_episode_content', 'episode', ['content_id'], unique=False)
    op.create_index('idx_episode_numbers', 'episode', ['content_id', 'season_number', 'episode_number'], unique=False)
    op.create_index('idx_episode_season', 'episode', ['season_id'], unique=False)
    op.create_index('idx_episode_tvdb', 'episode', ['tvdb_id'], unique=False)
    op.create_index(op.f('ix_episode_episode_number'), 'episode', ['episode_number'], unique=False)
    op.create_index(op.f('ix_episode_id'), 'episode', ['id'], unique=False)
    op.create_index(op.f('ix_episode_season_number'), 'episode', ['season_number'], unique=False)
    op.create_index(op.f('ix_episode_tvdb_id'), 'episode', ['tvdb_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episode_tvdb_id'), table_name='episode')
    op.drop_index(op.f('ix_episode_season_number'), table_name='episode')
    op.drop_index(op.f('ix_episode_id'), table_name='episode')
    op.drop_index(op.f('ix_episode_episode_number'), table_name='episode')
    op.drop_index('idx_episode_tvdb', table_name='episode')
    op.drop_index('idx_episode_season', table_name='episode')
    op.drop_index('idx_episode_numbers', table_name='episode')
    op.drop_index('idx_episode_content', table_name='episode')
    op.drop_index('idx_episode_aired', table_name='episode')
    op.drop_table('episode')
    op.drop_index(op.f('ix_season_tvdb_id'), table_name='season')
    op.drop_index(op.f('ix_season_season_number'), table_name='season')
    op.drop_index(op.f('ix_season_id'), table_name='season')
    op.drop_index('idx_season_tvdb', table_name='season')
    op.drop_index('idx_season_number', table_name='season')
    op.drop_index('idx_season_content', table_name='season')
    op.drop_table('season')
    # ### end Alembic commands ###
